version: "3.5"

services:
  spp-cal:
    image: cgrigis/spp-cal:latest
    build:
      context: .
      dockerfile: Dockerfile

    entrypoint:
      - hypercorn
      - --bind
      - 0.0.0.0:8000
      - /home/serve_calendar:app

    restart: unless-stopped

    volumes: []

    expose:
      - 8000
