name: Build and push Docker image, deploy on target

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build and push Docker image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: >
          docker build
          --tag cgrigis/spp-cal:latest
          --tag cgrigis/spp-cal:$(date +%s)
          --file Dockerfile
          .

      - name: Push
        if: github.event_name == 'push'
        run: >
          docker login
          --username ${{ secrets.DOCKER_USERNAME }}
          --password ${{ secrets.DOCKER_PASSWORD }} &&
          docker push -a cgrigis/spp-cal
